"""
Intervention and event scenarios for which to run the model and plot outcomes
"""

scenarios = {"Basic":{"fin_event_prob": 0.05,
                        "nonfin_event_prob": 0.05,
                        "rec_intervention_size" : 0,
                        "intervention_gap" : 10,
                        "int_ts": [],
                        "int_size": [],
                        "int_var": []},
            "Combination":{"fin_event_prob": 0.05,
                        "nonfin_event_prob": 0.05,
                        "rec_intervention_size" : 1,
                        "intervention_gap" : 10,
                        "int_ts": [10, 40],
                        "int_size": [1, 1],
                        "int_var": ["nonfin", "fin"]},
            "Only_fin_event": {"fin_event_prob": 0.05,
                        "nonfin_event_prob": 0.00,
                        "rec_intervention_size" : 0,
                        "intervention_gap" : 10,
                        "int_ts": [],
                        "int_size": [],
                        "int_var": []},
            "Only_nonfin_event": {"fin_event_prob": 0.00,
                        "nonfin_event_prob": 0.05,
                        "rec_intervention_size" : 0,
                        "intervention_gap" : 10,
                        "int_ts": [],
                        "int_size": [],
                        "int_var": []},
            "Only_rec_int_10": {"fin_event_prob": 0.00,
                        "nonfin_event_prob": 0.00,
                        "rec_intervention_size" : 1,
                        "intervention_gap" : 10,
                        "int_ts": [],
                        "int_size": [],
                        "int_var": []},
            "1_fin": {"fin_event_prob": 0.00,
                        "nonfin_event_prob": 0.00,
                        "rec_intervention_size" : 0,
                        "intervention_gap" : 10,
                        "int_ts": [10],
                        "int_size": [1],
                        "int_var": ["fin"]},
            "2_fin": {"fin_event_prob": 0.00,
                        "nonfin_event_prob": 0.00,
                        "rec_intervention_size" : 0,
                        "intervention_gap" : 10,
                        "int_ts": [10, 50],
                        "int_size": [1, 1],
                        "int_var": ["fin", "fin"]},
            "2_fin_posneg": {"fin_event_prob": 0.00,
                        "nonfin_event_prob": 0.00,
                        "rec_intervention_size" : 0,
                        "intervention_gap" : 10,
                        "int_ts": [10, 50],
                        "int_size": [1, -1],
                        "int_var": ["fin", "fin"]},
            "1_fin_1_nonfin": {"fin_event_prob": 0.00,
                        "nonfin_event_prob": 0.00,
                        "rec_intervention_size" : 0,
                        "intervention_gap" : 10,
                        "int_ts": [10, 50],
                        "int_size": [1, 1],
                        "int_var": ["fin", "nonfin"]}}